### ISSUE TITLE
Wrong password saved in /.initdbpwd

### ISSUE THREAD

**Issue by semabtariq1** [2ndQuadrant/postgres-installer#9]
Bug raised from the client via email to pginstaller@2ndquadrant.com

Hello

Today I downloaded Windows installer for postgresql 12 beta 3 from your pages.
Unfortunately the installation process failed just before finalizing the installation,

I narrowed it down to possible wrong password saved into file, which is then being passed to initdb command.
Installer asks for password for postgres and superuser roles. I've set two different passwords.
When installer failed, I found it uses the file stored in tmp directory, which contains a password set for the second role. Obviously it must have failed 'cause initdb is called with postgres role.

Running initdb with postgres role and proper password ended with success therefore I suspect this was the root cause. BTW error displayed by installer provides no much direct information about what failed. Hopefully it shows the command which failed, allowing to try it manually in command line.

**Comment by semabtariq1** [comment]
While debugging this issue I found out that we are saving database superuser password in initdbpwd file instead of Postgres user password 

https://github.com/2ndQuadrant/postgres-installer/blob/master/PGInstaller.xml.in

> Line number 410 to 413

**Suggestion**:

We should save Postgres user password in initdbpwd file

**Comment by haroon-github** [comment]
Semab, `postgres` user is the OS user that owns the server process and not the database superuser. Initidb needs database superuser password and that's what it should get.

**Comment by haroon-github** [comment]
@semabtariq1 or am I missing something ?

**Comment by semabtariq1** [comment]
> Semab, `postgres` user is the OS user that owns the server process and not the database superuser. Initidb needs database superuser password and that's what it should get.

Sure thats all right. Thanks for the clarification.
But now we can see a potential bug. 

We do not create OS user(postgres) on windows so on line number 430 there is a tag saying 

`<runAs>postgres</runAs>`

On windows, If postgres user does not exist and even if it exists again this tag can cause some confusion for OS/installBuilder and results in a failure. So 
We should limit this tag to Linux and macOS only

**Comment by semabtariq1** [comment]
We have added a condition in initdb command 
While running initdb on windows we run it without postgres user
